### ISSUE TITLE
Add error handling for all commands

### ISSUE THREAD

**Issue by NullPxl** [NullPxl/NullCTF#1]
https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#error-handling

**Comment by theKidOfArcrania** [comment]
Okay I personally ended up just registering an [on_command_error](https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.on_command_error) handler to handle command errors, plus an [on_error](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.on_error) hook to handle other errors.

For each case, I just have bot say that error occurred, and that's it: short and sweet.

**Comment by NullPxl** [comment]
Thanks!  I'll add it soon.

**Comment by NullPxl** [comment]
Added in latest commit
