### ISSUE TITLE
[Pull request made] bot can ping everyone using the reverse string feature

### ISSUE THREAD

**Issue by 0x0elliot** [NullPxl/NullCTF#15]
this can be pretty annoying considering it is in big servers. 

![image](https://user-images.githubusercontent.com/60684641/110911033-278ea880-8338-11eb-929a-1815d0d52376.png)

**Comment by 0x0elliot** [comment]
<a href="https://github.com/NullPxl/NullCTF/pull/16">Pull request which has the issue fixed :D</a>

**Comment by NullPxl** [comment]
Merged 👍 Thanks!
