### ISSUE TITLE
IS THE BOT STILL RUNNING?

### ISSUE THREAD

**Issue by krishyadav007** [NullPxl/NullCTF#20]
Is the bot's server still running, then the bot is not responding to any command

![image](https://user-images.githubusercontent.com/44264836/147926675-f8b3eb3c-d8be-4286-b1bd-954c93a1db11.png)
Images is attached

**Comment by Fumenoid** [comment]
Its working fine in JHDiscord, I am not sure which instance of bot you are running tho
![image](https://user-images.githubusercontent.com/47531747/147927725-fff17360-bed9-4c4b-b9d0-73b85700b051.png)

**Comment by krishyadav007** [comment]
> Its working fine in JHDiscord, I am not sure which instance of bot you are using tho 

I am running this one: https://discord.com/api/oauth2/authorize?client_id=885993913591140473&permissions=268561520&scope=bot

**Comment by NullPxl** [comment]
Sorry I missed this-- from what I can tell there hasn't been any bot-specific downtime ever since I moved to digital ocean for hosting. This was most likely due to discord's api which (according to their status page) was experience some issues around this time.
