### ISSUE TITLE
Auto challenges setup 

### ISSUE THREAD

**Issue by d347h4ck** [NullPxl/NullCTF#9]
Most modern cTFs use the ctfd platform to host. This platform has API to get challenges automatically, with get request https://ctfhost/api/v1/challenges, This request can be use for auto setup challenges to ctf.

**Comment by NullPxl** [comment]
Didn't know about this; great idea!

**Comment by NullPxl** [comment]
Added in https://github.com/NullPxl/NullCTF/commit/b050902587e9127b54cdc18d14cb3b22a388db15 via `>ctf challenge pull url`
